### ISSUE TITLE
Crosscompile guide

### ISSUE THREAD

**Issue by paulhybryant** [kovidgoyal/build-calibre#11]
Hello,

Can you also provide a crosscompile guide?
I am trying to use that on a device with arm cpu (not rasperry pi).

Thank you!

**Comment by kovidgoyal** [comment]
sorry I've never cross compiled calibre (or anything really), so ihave no idea, sorry.

**Comment by paulhybryant** [comment]
ok. Thank you for the reply.

May I ask where is the source code for ebook-convert?
I tried to locate it in the source code but failed to find it.

What I want to do is to compile just the ebook-convert binary myself.

**Comment by kovidgoyal** [comment]
There is no separate source code. The binaries are just thin wrappers.
You cannot build one of them separately from the others.

**Comment by paulhybryant** [comment]
Thin wrappers of what binaries?
For example, because I just want to invoke ebook-convert in cli, I prefer not to compile everything with the qt dependencies.

**Comment by kovidgoyal** [comment]
thin wrappers that launch python. And the conversion system uses Qt, for
example, for image processing.

**Comment by paulhybryant** [comment]
I see. Thanks!
