### ISSUE TITLE
Compile error when compiling ISO639 files

### ISSUE THREAD

**Issue by paulhybryant** [kovidgoyal/build-calibre#12]
Hi,

I managed to install most dependencies, and ran into an error that I cannot understand:

Compiling ISO639 files...
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    sys.exit(main())
  File "setup.py", line 106, in main
    command.run_all(opts)
  File "/root/calibre/setup/__init__.py", line 242, in run_all
    self.run_cmd(self, opts)
  File "/root/calibre/setup/__init__.py", line 234, in run_cmd
    self.run_cmd(scmd, opts)
  File "/root/calibre/setup/__init__.py", line 238, in run_cmd
    cmd.run(opts)
  File "/root/calibre/setup/translations.py", line 276, in run
    self.compile_main_translations()
  File "/root/calibre/setup/translations.py", line 369, in compile_main_translations
    self.compile_group(files, file_ok=self.check_iso639)
  File "/root/calibre/setup/translations.py", line 307, in compile_group
    if file_ok is None or file_ok(data, src):
  File "/root/calibre/setup/translations.py", line 439, in check_iso639
    cm = langnames_to_langcodes([omsgid, msgid])
  File "/root/calibre/src/calibre/utils/localization.py", line 448, in langnames_to_langcodes
    iso639 = _load_iso639()
  File "/root/calibre/src/calibre/utils/localization.py", line 354, in _load_iso639
    _iso639 = msgpack_loads(ip)
  File "/root/calibre/src/calibre/utils/serialize.py", line 109, in msgpack_loads
    return msgpack.unpackb(dump, ext_hook=msgpack_decoder, raw=False)
  File "msgpack/_unpacker.pyx", line 211, in msgpack._unpacker.unpackb
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0

Can you shed some light on what is the root cause of this compile error?

Thank!

**Comment by kovidgoyal** [comment]
What were you running when that happened? Remember that you need a
bootstrapped calibre checkout to build calibre. On the main linux
computer, run ./setup.py bootstrap

and only after that can you use it to build the various binary calibre
distributions.

**Comment by paulhybryant** [comment]
That is the error I got when I run 
python setup.py bootstrap

I took a deeper look at the error, and the file:
./resources/localization/iso639.calibre_msgpack
is empty

**Comment by paulhybryant** [comment]
Can it be because I ran into some error previously (e.g. missing header files) and need to cleanup some intermediate files?

I spotted this in the console
*
* Running iso639
*

Pickled code is up to date
* iso639 took 0.0 seconds

**Comment by kovidgoyal** [comment]
Run

./setup.py iso639 --clean
./setup.py iso639

to regenerate it. See if it generates a proper file this time.

**Comment by paulhybryant** [comment]
Thanks, that solves it.

Should I install kovidgoyal/dukpy for the dukpy dependency?
After regenerating iso639, it reports not found module about dukpy

I am asking because I also see another py module, with the same name amol-/dukpy

**Comment by kovidgoyal** [comment]
yes kovidgoyal/dukpy

**Comment by paulhybryant** [comment]
Thank you very much for your help.
Everything works fine now.

**Comment by paulhybryant** [comment]
Hello again,

Is the instruction after bootstrap outdated?
After bootstraping, I cannot find any executable named linux
The instruction says ./linux 64 calibre
I assume this is run under the source directory of calibre?

**Comment by kovidgoyal** [comment]
No this executable is in the build-calibre repo, not calibre.

**Comment by paulhybryant** [comment]
Running ./linux 64 got the following error:

......
in-chroot apt-get clean
in-chroot chsh -s /bin/zsh build-calibre
sudo chown 1001:1001 /home/build-calibre/bca/build/linux/64/chroot-1
mount: /home/build-calibre/bca/build/linux/64/chroot-1/tmp: permission denied.

**Comment by kovidgoyal** [comment]
no idea, you likely have some system policies in place to prevent bind mounting or similar. Look at the linux script its a simple script of a few hundred lines, in this case mount_all() function and see what mount call exactly is failing.

**Comment by paulhybryant** [comment]
ok. I will dig more to investigate. I am running this in docker, that maybe the reason.
Thanks for all the reply!
