### ISSUE TITLE
python setup.py bootstrap broken

### ISSUE THREAD

**Issue by paulhybryant** [kovidgoyal/build-calibre#14]
It is broken by the migration of css parser.

**Comment by kovidgoyal** [comment]
broken how? with what error? Works for me, as long as css-parser is installed.

**Comment by paulhybryant** [comment]
yeah, I installed css-parser and it works fine.
What I means is dukpy and css-parser both need to be installed for bootstrap to work.
It would be good to mentioned that in the README.

**Comment by kovidgoyal** [comment]
There are a whole bunch of things that need to be installed for
bootstrapping to work, the entire list is mentioned on the linux
download page via a link to the calibre-build dependencies file.
