### ISSUE TITLE
Failed to import site module::No module named site

### ISSUE THREAD

**Issue by paulhybryant** [kovidgoyal/build-calibre#15]
Hello,

I managed to built the binaries successfully for armhf.
The command CALIBRE_SRC_DIR=... ./linux 32 calibre created the binary packages (calibre-3.37.0-i686.txz). I extracted the archive to /opt/calibre, and ebook-convert (or similarly other binaries) return the error "Failed to import site module::No module named site".

Can you shed some light on what might have gone wrong?
Thanks!

**Comment by paulhybryant** [comment]
And FYI, the system I am running the binary have python installed,
and I also tried setting PYTHONHOME and PYTHONPATH, but that is not working.

**Comment by paulhybryant** [comment]
From the code it seems the launchers will ignore these variables.
The binaries run fine within the env where it is built (in a docker container with the rootfs of ubuntu precise for armhf).
It fails to run in the docker container I need to use (which is based on alpine for armhf)

Rebuilt the binaries with some logs:
Path before Py_Initialize(): lib/python27.zip:lib/python2.7/:lib/python2.7/plat-linux2:lib/python2.7/lib-tk:lib/python2.7/lib-old:lib/python2.7/lib-dynload

Path after Py_Initialize(): lib/python27.zip:lib/python2.7/:lib/python2.7/plat-linux2:lib/python2.7/lib-tk:lib/python2.7/lib-old:lib/python2.7/lib-dynload

Path set by me: /lib/python2.7:/lib/python2.7/plat-linux2:/lib/python2.7/lib-dynload:/lib/python2.7/site-packages

The last one doesn't seem right as the python libraries are at /usr/lib.
However, in the ubuntu system the python library is installed at the same location (/usr/lib), but the binaries run fine.

**Comment by kovidgoyal** [comment]
When you build the calibre libraries, they contain their own python, they do not use the system python. THere should be absolute paths in sys.path. I have no idea why you seem to have relative paths. And what does path set by me mean? See the get_paths() function in linux/util.c to see how the binaries setup their paths.

**Comment by paulhybryant** [comment]
The path set by me message is from the existing code (I uncommented it):
https://github.com/kovidgoyal/build-calibre/blob/396688621863d0eaa364e7a9ff4053dc6a9a3187/scripts/freeze/linux/util.c#L209
It means that is the path set by this binary.

**Comment by paulhybryant** [comment]
Shouldn't it be relative path? If it is going to use the python packages included with the calibre distribution. I think the problem is because it has absolute path?

**Comment by paulhybryant** [comment]
NVM, reading the code more, it should have the absolute path of the lib directory (e.g. /opt/calibre/lib/...).
But somehow /opt/calibre is gone (the binary is invoked like /opt/calibre/ebook-convert)
That is indeed wired.

**Comment by paulhybryant** [comment]
ok. I think this is due to some implementation difference (likely a bug in the library being used).
The same binary in the ubuntu container output differently:

Path before Py_Initialize(): /opt/calibre/lib/python27.zip:/opt/calibre/lib/python2.7/:/opt/calibre/lib/python2.7/plat-linux2:/opt/calibre/lib/python2.7/lib-tk:/opt/calibre/lib/python2.7/lib-old:/opt/calibre/lib/python2.7/lib-dynload

Path after Py_Initialize(): /opt/calibre/lib/python27.zip:/opt/calibre/lib/python2.7/:/opt/calibre/lib/python2.7/plat-linux2:/opt/calibre/lib/python2.7/lib-tk:/opt/calibre/lib/python2.7/lib-old:/opt/calibre/lib/python2.7/lib-dynload

Path set by me: /opt/calibre/lib/python2.7:/opt/calibre/lib/python2.7/plat-linux2:/opt/calibre/lib/python2.7/lib-dynload:/opt/calibre/lib/python2.7/site-packages

This one gives the correct path.

**Comment by kovidgoyal** [comment]
Like I said, look at get_paths() Most likely an issue with the /proc filesystem not being mounted or malfunctioning in the container.

**Comment by paulhybryant** [comment]
ok. Thanks for clarifying that. Seems that is only causing issue for armhf, not x86.
