### ISSUE TITLE
SQLite download page not found (sources.json)

### ISSUE THREAD

**Issue by rashuf** [kovidgoyal/build-calibre#3]
Hi, Kovid :)
During building calibre SQLite download page not found. True address is https://www.sqlite.org/2017/sqlite-autoconf-3130000.tar.gz
Correct the file sources.json
  "name": "sqlite",
        "unix": {
            "filename": "sqlite-autoconf-3130000.tar.gz",
            "hash": "sha1:f6f76e310389e3f510b23826f805850449ae8653",
            "urls": ["https://www.sqlite.org/2017/{filename}"]
        }

**Comment by kovidgoyal** [comment]
Looks correct to me:

```
curl -I https://www.sqlite.org/2016/sqlite-autoconf-3130000.tar.gz                                                                                                                                                                     
HTTP/1.1 200 OK
Connection: keep-alive
Date: Fri, 05 Jan 2018 11:45:27 +0000
Last-Modified: Thu, 04 Aug 2016 14:08:46 +0000
Content-type: application/x-gzip
Content-length: 2459805
```
