### ISSUE TITLE
Build hangs at downloading libgcrypt for infinite time

### ISSUE THREAD

**Issue by gberes01** [kovidgoyal/build-calibre#7]
gabi@gabi-XPS-13-9350 ~/Downloads/build-calibre $ ./linux 64
sudo mkdir -p /home/gabi/Downloads/build-calibre/build/linux/64/container-1/usr/share/terminfo/x
sudo cp -a /lib/terminfo/x/xterm-256color /home/gabi/Downloads/build-calibre/build/linux/64/container-1/usr/share/terminfo/x
sudo chroot --userspec=1000:1000 /home/gabi/Downloads/build-calibre/build/linux/64/container-1 python2 /scripts/main.py

Downloading libgcrypt-1.7.1.tar.bz2 from ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.7.1.tar.bz2

**Comment by kovidgoyal** [comment]
Works for me. In any case you can always manually download it and place it in the sources-cache if for some reason it is not downloading for you.
