### ISSUE TITLE
acbuild -> docker migration

### ISSUE THREAD

**Issue by gberes01** [kovidgoyal/build-calibre#8]
Acbuild is not maintained anymore and it is not available in mainstream distributions. You need to install from source. How about using Docker instead?

**Comment by kovidgoyal** [comment]
The build process does not use containers, it uses chroot, as such docker is not suitable. If you have some other tool that can build the chroot from images on dockerhub (or elsewhere), I'll be happy to accept a PR.

**Comment by gberes01** [comment]
I was mainly thinking about creating a Docker image with the dependencies and build calibre on top of that. Building all the dependencies from source takes a lot of time, and also seems unnecessary.

**Comment by kovidgoyal** [comment]
Why does one need a docker image for that? You simply need to pass around the ./build directory. Use tar for that. And the time it takes to build the dependencies is one time, you dont need to do it again unless you change a version of a dependency and then you only need to rebuild that single dependency.
